#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
%define keepstatic 1
Name     : python2-mod_wsgi
Version  : 4.5.24
Release  : 49
URL      : https://github.com/GrahamDumpleton/mod_wsgi/archive/4.5.24.tar.gz
Source0  : https://github.com/GrahamDumpleton/mod_wsgi/archive/4.5.24.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: python2-mod_wsgi-bin = %{version}-%{release}
Requires: python2-mod_wsgi-license = %{version}-%{release}
Requires: python2-mod_wsgi-python = %{version}-%{release}
BuildRequires : apr-dev
BuildRequires : apr-util-dev
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : httpd-data
BuildRequires : httpd-dev
BuildRequires : httpd-extras
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv
Patch1: 0001-defaults.patch

%description
Overview
--------
The mod_wsgi package provides an Apache module that implements a WSGI
compliant interface for hosting Python based web applications on top of the
Apache web server.

%package bin
Summary: bin components for the python2-mod_wsgi package.
Group: Binaries
Requires: python2-mod_wsgi-license = %{version}-%{release}

%description bin
bin components for the python2-mod_wsgi package.


%package legacypython
Summary: legacypython components for the python2-mod_wsgi package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the python2-mod_wsgi package.


%package license
Summary: license components for the python2-mod_wsgi package.
Group: Default

%description license
license components for the python2-mod_wsgi package.


%package python
Summary: python components for the python2-mod_wsgi package.
Group: Default

%description python
python components for the python2-mod_wsgi package.


%prep
%setup -q -n mod_wsgi-4.5.24
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539990057
export CFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FCFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export FFLAGS="$CFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
export CXXFLAGS="$CXXFLAGS -O3 -falign-functions=32 -fno-math-errno -fno-semantic-interposition -fno-trapping-math "
python2 setup.py build -b py2

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/python2-mod_wsgi
cp LICENSE %{buildroot}/usr/share/package-licenses/python2-mod_wsgi/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mod_wsgi-express

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/python2-mod_wsgi/LICENSE

%files python
%defattr(-,root,root,-)
